### ISSUE TITLE
Bug: Edit reports error but post was edited

### ISSUE THREAD

**Issue by gingerbeardman** [SUWULLC/Octal#307]
Editing a comment and pressing save can sometimes show an error. 

Most of the time the edit has been successful. 
But sometimes the edit has not been done.

So you have to check the website.

![image](https://github.com/user-attachments/assets/70b2dc53-ad92-4220-b463-01f5e33e43c4)

**Comment by luckman212** [comment]
I have this problem too. I usually end up going to the website to edit/confirm that the comment was correctly saved.

**Comment by dangwu** [comment]
What's likely occurring is that you are being rate limited by HN API. On the web, you'd see a "Sorry, we can't service your requests this quickly" error, but often if you check the comment, the edit would actually goes through despite the error. You can reproduce this yourself by sending a posting a few edits or comments in quick succession. 

I *could* make this error more transparent on Octal, as right now all errors show up as this generic "Something went wrong" alert. But the issue is that it's truly difficult to work with the (undocumented) HN write API *and* the site aggressively bans/shadowbans/rate limits people for messing around... (e.g. there's no QA environment), so I'm weary of going too deep into this stuff.

**Comment by gingerbeardman** [comment]
Makes sense, I guess we would need to know their limits. But I would not say that I was editing much at all when getting this. Definitely not an amount I would consider too much. :)

**Comment by dangwu** [comment]
I believe you. I just can’t tell why the app hits the limits so quickly
compared to a real web browser

**Comment by gingerbeardman** [comment]
Maybe the app could offer up the web view when getting this error after editing? Would at least make it quicker to check if it went through.

**Comment by dangwu** [comment]
This might be resolved now. Let me know if it's still an issue

**Comment by gingerbeardman** [comment]
Does seem fixed. 

What was the problem?

**Comment by dangwu** [comment]
Awesome. There was a bug where the app was polling for favorites repeatedly if you had 30+, thus it was way more likely to hit the API threshold
