### ISSUE TITLE
"Something went wrong" when logging in

### ISSUE THREAD

**Issue by sbc** [SUWULLC/Octal#319]
On version 4.16.2 on iOS 18.0.1.

Was suddenly logged out of Octal and getting this message when trying to log back in: "Something went wrong: Please try again later". 

I am able to log into the HN website just fine.

**Comment by dangwu** [comment]
I've just been told by HN they're blocking these HTTP web requests (sign in, favorite, reply, etc) from Octal due to excessive/unauthorized usage. It was frowned upon for Octal to be making these calls in the first place, as they aren't part of the public Firebase API.

As saddening as it is, I think there's nothing I can do at this point. I may have to update the app to make it a read-only experience.

**Comment by dangwu** [comment]
It should be fixed now with the 4.16.3 update today. Let me know if it persists
